
                    
                            
                            <!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="Cache-Control" content="no-cache" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />           
        <meta property="og:title" content="FQCI: Health Tips " />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="Naturally, human body is organized in such a way that when we do the right thing at the right time, there will be no reason for us to get sick or get old before old age. To maintain a healthy living we need to the following:  1. Detoxify: We accumulate a lot of toxins through the air we breathe, the water we drink, the food we eat. Greenlife Detoxin tablet will assist our body system to get rid of toxins. It is an internal cleanser & blood purifier, it transports oxygen to the brain. Detoxin cleanses the system of foreign substances, body waste products, toxins and free radiates that get into the body through inhalation of polluted air, food and vegetables planted with fertilizers and the use of herbicides, pesticides on plants, chemicals from orthodox drug and so on. Other internal detoxifiers are; Royal teal, Angel tea and Haem Pill.  2. Build your Immune System: Our immune system is the body defense: it protects our body from foreign invader of pathogens. Greenlife Booster Drink is an immune booster. Low 1mm unity can allow all kind of different diseases to invade our body system.  3. Achieve Micro Circulation: Blood is life; it is the chief transporter in our body system. Blood transports oxygen and nutrients to the body tissues. Cholesterol/blood lips block the passage for blood in the blood vessels, the vein, arteries and capillaries. Lack of normal blood flow can cause a lot of heart diseases such as high blood pressure, diabetes, stroke, angina pectoris and end result CARDIAC ARREST. Use Greenlife’s Danshen plus to achieve micro circulation (Blood Circulation at capillary Level) as different type of messengers will help you for normal blood circulation." />
        <meta property="og:image" content="http://192.168.173.1/femquen/health-doctor/image/719a1.png" />
        <meta name="description" content="FQCI: Naturally, human body is organized in such a way that when we do the right thing at the right time, there will be no reason for us to get sick or get old before old age. To maintain a healthy living we need to the following:  1. Detoxify: We accumulate a lot of toxins through the air we breathe, the water we drink, the food we eat. Greenlife Detoxin tablet will assist our body system to get rid of toxins. It is an internal cleanser & blood purifier, it transports oxygen to the brain. Detoxin cleanses the system of foreign substances, body waste products, toxins and free radiates that get into the body through inhalation of polluted air, food and vegetables planted with fertilizers and the use of herbicides, pesticides on plants, chemicals from orthodox drug and so on. Other internal detoxifiers are; Royal teal, Angel tea and Haem Pill.  2. Build your Immune System: Our immune system is the body defense: it protects our body from foreign invader of pathogens. Greenlife Booster Drink is an immune booster. Low 1mm unity can allow all kind of different diseases to invade our body system.  3. Achieve Micro Circulation: Blood is life; it is the chief transporter in our body system. Blood transports oxygen and nutrients to the body tissues. Cholesterol/blood lips block the passage for blood in the blood vessels, the vein, arteries and capillaries. Lack of normal blood flow can cause a lot of heart diseases such as high blood pressure, diabetes, stroke, angina pectoris and end result CARDIAC ARREST. Use Greenlife’s Danshen plus to achieve micro circulation (Blood Circulation at capillary Level) as different type of messengers will help you for normal blood circulation.">
        <meta name="keywords" content="FQCI,Health,Doctor,Health Tips,Naturally, human body is organized in such a way that when we do the right thing at the right time, there will be no reason for us to get sick or get old before old age. To maintain a healthy living we need to the following:  1. Detoxify: We accumulate a lot of toxins through the air we breathe, the water we drink, the food we eat. Greenlife Detoxin tablet will assist our body system to get rid of toxins. It is an internal cleanser & blood purifier, it transports oxygen to the brain. Detoxin cleanses the system of foreign substances, body waste products, toxins and free radiates that get into the body through inhalation of polluted air, food and vegetables planted with fertilizers and the use of herbicides, pesticides on plants, chemicals from orthodox drug and so on. Other internal detoxifiers are; Royal teal, Angel tea and Haem Pill.  2. Build your Immune System: Our immune system is the body defense: it protects our body from foreign invader of pathogens. Greenlife Booster Drink is an immune booster. Low 1mm unity can allow all kind of different diseases to invade our body system.  3. Achieve Micro Circulation: Blood is life; it is the chief transporter in our body system. Blood transports oxygen and nutrients to the body tissues. Cholesterol/blood lips block the passage for blood in the blood vessels, the vein, arteries and capillaries. Lack of normal blood flow can cause a lot of heart diseases such as high blood pressure, diabetes, stroke, angina pectoris and end result CARDIAC ARREST. Use Greenlife’s Danshen plus to achieve micro circulation (Blood Circulation at capillary Level) as different type of messengers will help you for normal blood circulation.">
        <meta name="creation-date" content="2019">
        <meta name="revisit-after" content="15 days">
        <title>FQCI: Health Tips</title>
        <link rel="stylesheet" href="../template/lib/w3.css">         
        <link rel="stylesheet" href="../template/font-awesome/css/font-awesome.min.css">
        <link rel="icon" href="../media/image/icon/icon.png" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="../template/css/index.css">
        <script type="text/javascript" src="../template/js/jquerym.js"></script>
        <script type="text/javascript" src="../template/js/index.js"></script>
    </head>
    <body class="w3-padding-0 w3-margin-0">
        <div id="body" class="w3-container w3-padding-0 w3-margin-0">
            
            <?php
                //import header
                include("config/new-header.php");
            ?>
            
            <div id="content" class="w3-container w3-padding-0 w3-margin-0">
                
                <?php /* site content goes here */?>
                
                <div class="w3-container w3-margin">
                    
                    <div>
                        <h1 class="w3-center w3-text-shadow" title="Health Tips" style="text-transform:uppercase;">Health Tips</h1>
                    </div>
                    
                    <div>
                        <img class="w3-responsive" src="http://192.168.173.1/femquen/health-doctor/image/719a1.png" style="width: 100%; height: 600px;" alt="Health Tips">
                    </div>
                    
                    <div class="w3-margin">
                        <p style="margin-left:0in; margin-right:0in; text-align:center"><span style="font-size:20px"><span style="font-family:Calibri"><strong>Basic Health Tips:</strong></span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">Naturally, human body is </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">organized in such a way that when we do the right thing at the right </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">time, there will be no reason for us </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">to get sick or get old before old </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">age. </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">To maintain a healthy living we </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">need to the following:</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">1. <strong>Detoxify:</strong> We accumulate a </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">lot of toxins through the air we </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">breathe, the water we drink, the </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">food we eat. Greenlife Detoxin </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">tablet will assist our body system </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">to get rid of toxins. It is an internal </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">cleanser & blood purifier, it </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">transports oxygen to the brain. </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">Detoxin cleanses the system of </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">foreign substances, body waste </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">products, toxins and free radiates </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">that get into the body through </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">inhalation of polluted air, food and vegetables planted with fertilizers and the use of </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">herbicides, pesticides on plants, chemicals from orthodox drug and so on. Other </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">internal detoxifiers are; Royal teal, Angel tea and Haem Pill.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">2. <strong>Build your Immune System: </strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">Our immune system is the body defense: it </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">protects our body from foreign invader of </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">pathogens. Greenlife Booster Drink is an </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">immune booster. Low 1mm unity can allow all kind </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">of different diseases to invade our body system.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">3. <strong>Achieve Micro Circulation: </strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">Blood is life; it is the chief transporter in our body </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">system. Blood transports oxygen and nutrients to </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">the body tissues. Cholesterol/blood lips block the </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">passage for blood in the blood vessels, the vein, </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">arteries and capillaries. Lack of normal blood flow </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">can cause a lot of heart diseases such as high </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">blood pressure, diabetes, stroke, angina pectoris </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">and end result <strong>CARDIAC ARREST</strong>. Use </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">Greenlife’s Danshen plus to achieve micro </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">circulation (Blood Circulation at capillary Level) as </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">different type of messengers will help you for </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">normal blood circulation.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">4. <strong>Take the right Nutrients: </strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">We need balance diet to </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">keep healthy at cellular </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">level. Because of the poor </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">economic condition of our </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">environment, busy </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">schedule, or ignorance, we </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">end up not taking what we </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">need but taking what we </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">can afford or what we want. </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">The red and white blood </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">cells renew itself every </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">seven years, but due to lack </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">of proper nutrients, they </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">break down and this can </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">result to formation of radical cells that destroys even the morel </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">cells and this can result to a lot of malfunctions ¡n the body system, abnormal </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">growths such as lumps, fibroid, cancer and so on. To prevent a lot of diseases, </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">we need to take the six classes of food at their proper proportion. The alkaline </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">and acidic contents of our food intake is also important.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">5. <strong>Avoid Stress: S</strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">tress is a silent killer disease. Stress </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">upsets the body normal balance, </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">creating the breeding space for so </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">many illnesses such as cardiovascular </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">disease, cancer, endocrine system </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">diseases, metabolic disease and </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">infection of different kinds. Stress is </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">said to have contributed up to 80% of </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">major illness. When we are under </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">stress, the body naturally responses </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">with the fight of flight mechanism of the </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">I renal gland. This response from the </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">body can result to the increase of </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">adrenalin secretion, high blood pressure, increase heart beat, tension ¡n the </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">muscles, digestive problems. Fat and Glucose are release into the blood </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">stream: the pituitary gland increases the production of adrenocortropic </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">hormone stimulating the release of cortisone and cortisol hormone.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">5. <strong>Alkaline water: </strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">This is water that is less </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">acidic than regular </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">rich in alkaline corn </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">silica, potassium, magnesium, </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">carbonate etc. When your water is boiled or </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">processed through chemical process of </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">purification, nutritional values and reduced </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">or gone totally and as a result the natural </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">nutritional benefit our body derives from </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">water will be no longer there. <strong>WATER IS </strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri"><strong>LIFE</strong> as the saying goes but when we take </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">contaminated water it becomes a </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri"><strong>DISEASE</strong>. </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">When we take chemically processed water the natural nutrients will not be there and it becomes acidic water that will cause different diseases to the body.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri"> * </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri"><strong>Benefit of Alkaline water:</strong></span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">- It restores PH balance by reducing acidity levels in the body.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">- Anti-oxidant helps </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">to neutralize free radicals that can cause cellular and DNA damage.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">- Alkaline is a natural detoxifier, it eliminates mucus build- up on colon walls thus</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">- improves the ability of the body to absorb important nutrients. </span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">- It flushes out </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">acidic waste and toxins that have accumulated in the body over time.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri">- It rejuvinates/energizes the entire body.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri"> </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri"><strong>GREENLIFE WATER TREATMENT MACHINE </strong></span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">Will help you to produce natural treated and alkaline PH water level 7.1 right </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">there in your home. 8 -12 glasses of water is the daily W.H.O water </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">requirements.</span></span></p>

<p style="margin-left:0in; margin-right:0in"><span style="font-size:11.0pt"><span style="font-family:Calibri"><strong>6. SLEEP:</strong> Is a natural way to relax, rejuvenate, and revitalize the body organs. </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri"><strong>A BETTER SLEEPS MEANS A BETTER YOU:</strong> sleeps helps you to reduce </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">stress, improves your memory, lower high blood pressure, builds your immune </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">system and sleep puts you in a better mood. A good night sleep is vital to your </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">physical health and emotional health. Our body is designed to have 8 hrs night </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">sleep and 2 hours day sleep but we’re too busy and ¡n a civilized society. If </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">because had to make out time to sleep and even when we have time to sleep, it </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">does not come because of stress and work load accumulated on our central </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">nervous system, it becomes difficult to have the daily required hours of sleep or </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">even to have deep sleep. </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">Greenlife <strong>B-care, relaxing pill, Herbal steam machine, and Healthy life mat</strong> can </span></span><span style="font-size:11.0pt"><span style="font-family:Calibri">help restore your natural sleep.</span></span></p>

                    </div>
                    
                </div>
                
            </div>
            
            <?php
                //import footer
                include("../include/footer.php");
            ?>
            
        </div>
    </body>
</html>

                    
                    
                    